product_html_string = '''
<li id="result_0" data-asin="B01B4NLOW4" class="s-result-item celwidget  "><div class="s-item-container"><div class="a-fixed-left-grid"><div class="a-fixed-left-grid-inner" style="padding-left:218px"><div class="a-fixed-left-grid-col a-col-left" style="width:218px;margin-left:-218px;float:left;"><div class="a-row"><div aria-hidden="true" class="a-column a-span12 a-text-center"><a class="a-link-normal a-text-normal" href="https://www.amazon.com/Marvel-Legends-Iron-Electronic-Helmet/dp/B01B4NLOW4/ref=sr_1_1?ie=UTF8&amp;qid=1526927761&amp;sr=8-1&amp;keywords=iron+man+helmet"><img src="https://images-na.ssl-images-amazon.com/images/I/51+tIG3fxGL._AC_US218_.jpg" srcset="https://images-na.ssl-images-amazon.com/images/I/51+tIG3fxGL._AC_US218_.jpg 1x, https://images-na.ssl-images-amazon.com/images/I/51+tIG3fxGL._AC_US327_QL65_.jpg 1.5x, https://images-na.ssl-images-amazon.com/images/I/51+tIG3fxGL._AC_US436_QL65_.jpg 2x, https://images-na.ssl-images-amazon.com/images/I/51+tIG3fxGL._AC_US500_QL65_.jpg 2.2935x" alt="Marvel Legends Iron Man Electronic Helmet" class="s-access-image cfMarker" data-search-image-load="" width="218" height="218"></a><div class="a-section a-spacing-none a-text-center"></div></div></div></div><div class="a-fixed-left-grid-col a-col-right" style="padding-left:2%;float:left;"><div class="a-row a-spacing-small"><div class="a-row a-spacing-none"><a class="a-link-normal s-access-detail-page  s-color-twister-title-link a-text-normal" title="Marvel Legends Iron Man Electronic Helmet" href="https://www.amazon.com/Marvel-Legends-Iron-Electronic-Helmet/dp/B01B4NLOW4/ref=sr_1_1?ie=UTF8&amp;qid=1526927761&amp;sr=8-1&amp;keywords=iron+man+helmet"><h2 data-attribute="Marvel Legends Iron Man Electronic Helmet" data-max-rows="0" class="a-size-medium s-inline  s-access-title  a-text-normal">Marvel Legends Iron Man Electronic Helmet</h2></a></div><div class="a-row a-spacing-none"><span class="a-size-small a-color-secondary">by </span><span class="a-size-small a-color-secondary">Avengers</span></div></div><div class="a-row"><div class="a-column a-span7"><div class="a-row a-spacing-none"><a class="a-link-normal a-text-normal" href="https://www.amazon.com/Marvel-Legends-Iron-Electronic-Helmet/dp/B01B4NLOW4/ref=sr_1_1?ie=UTF8&amp;qid=1526927761&amp;sr=8-1&amp;keywords=iron+man+helmet"><span class="a-offscreen">$304.86</span><span aria-hidden="true" class="a-color-base sx-zero-spacing"><span class="sx-price sx-price-large">
                            <sup class="sx-price-currency">$</sup>
                            <span class="sx-price-whole">304</span>
                            <sup class="sx-price-fractional">86</sup>
                        </span>
                    </span></a><span class="a-letter-space"></span><i class="a-icon a-icon-prime a-icon-small s-align-text-bottom" aria-label="Prime"><span class="a-icon-alt">Prime</span></i></div><div class="a-row a-spacing-mini"><div class="a-row a-spacing-none"><span class="a-size-small a-color-secondary">Get it by <span class="a-color-success a-text-bold">Thursday, May 31</span></span></div><div class="a-row a-spacing-none"><span class="a-size-small a-color-secondary">FREE Shipping on eligible orders</span></div></div><div class="a-row a-spacing-mini"><div class="a-row a-spacing-none"><div class="a-row a-spacing-mini"></div><span class="a-size-small a-color-secondary">More Buying Choices</span></div><div class="a-row a-spacing-none"><a class="a-size-small a-link-normal a-text-normal" href="https://www.amazon.com/gp/offer-listing/B01B4NLOW4/ref=sr_1_1_olp?ie=UTF8&amp;qid=1526927761&amp;sr=8-1&amp;keywords=iron+man+helmet&amp;condition=new"><span class="a-color-secondary a-text-strike"></span><span class="a-size-base a-color-base">$289.99</span><span class="a-letter-space"></span>(9 new offers)</a></div></div></div><div class="a-column a-span5 a-span-last"><div class="a-row a-spacing-mini"><span name="B01B4NLOW4">
    <span class="a-declarative" data-action="a-popover" data-a-popover="{&quot;max-width&quot;:&quot;700&quot;,&quot;closeButton&quot;:&quot;false&quot;,&quot;position&quot;:&quot;triggerBottom&quot;,&quot;url&quot;:&quot;/review/widgets/average-customer-review/popover/ref=acr_search__popover?ie=UTF8&amp;asin=B01B4NLOW4&amp;contextId=search&amp;ref=acr_search__popover&quot;}"><a href="javascript:void(0)" class="a-popover-trigger a-declarative"><i class="a-icon a-icon-star a-star-4-5"><span class="a-icon-alt">4.3 out of 5 stars</span></i><i class="a-icon a-icon-popover"></i></a></span></span>

<a class="a-size-small a-link-normal a-text-normal" href="https://www.amazon.com/Marvel-Legends-Iron-Electronic-Helmet/dp/B01B4NLOW4/ref=sr_1_1?ie=UTF8&amp;qid=1526927761&amp;sr=8-1&amp;keywords=iron+man+helmet#customerReviews">306</a></div><div class="a-row a-spacing-mini"><span class="a-size-small a-color-secondary">Manufacturer recommended age: 15 Years and up</span></div><div class="a-row a-spacing-mini"><span class="a-size-small a-color-secondary a-text-bold">Product Features</span><br><span class="a-size-small a-color-secondary">Includes <em>Iron Man</em> electronic <em>helmet</em> and instructions</span></div></div></div></div></div></div></div></li>'''

